#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTServo,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftb,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftf,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightb,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     rightf,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    cubedropper,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    cubelifter,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//servo dropper is 50 is up; 145 is drop the cube
//servo lifter is stop 128; 255 is go; 0 is backwards


#include "JoystickDriver.c"
	void forward(int sec){
	motor[leftb]=60;
	motor[leftf]=60;
	motor[rightb]=60;
	motor[rightf]=60;
	wait10Msec(sec);
	motor[leftb]=0;
	motor[leftf]=0;
	motor[rightb]=0;
	motor[rightf]=0;
}

void turnleft(int sec){
	motor[leftb]=-50;
	motor[leftf]=-50;
	motor[rightb]=50;
	motor[rightf]=50;
	wait10Msec(sec);// divide by 100 to get #of sec
	motor[leftb]=0;
	motor[leftf]=0;
	motor[rightb]=0;
	motor[rightf]=0;
}

void turnright(int sec){
	motor[leftb]=50;
	motor[leftf]=50;
	motor[rightb]=-50;
	motor[rightf]=-50;
	wait10Msec(sec);
	motor[leftb]=0;
	motor[leftf]=0;
	motor[rightb]=0;
	motor[rightf]=0;
}

void backward(int sec){
	motor[leftb]=-60;
	motor[leftf]=-60;
	motor[rightb]=-60;
	motor[rightf]=-60;
	wait10Msec(sec);
	motor[leftb]=0;
	motor[leftf]=0;
	motor[rightb]=0;
	motor[rightf]=0;
}
//servo dropper is 50 is up; 145 is drop the cube
//servo lifter is stop 128; 255 is go; 0 is backwards
task main()//tested when it ramp is at the left
{
waitForStart();
servo[cubedropper]=50;
servo[cubelifter]=255;
wait10Msec(400);
backward(65);
servo[cubelifter]=255;
servo[cubedropper]=145;
forward(65);
//ramp
backward(10);
turnleft(100);//150 turns about 90 75 is about 30
backward(120);
turnright(187);
backward(170);
servo[cubelifter]=0;
wait10Msec(400);
}
