#pragma config(Sensor, S2,     colorSensor,    sensorCOLORFULL)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorB,           top,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           base,             tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define threshold 3
//Initiate Variables
int baseVal;
int topVal;
int baseStartingPos;
int topStartingPos;

void debug(){
		nxtDisplayCenteredTextLine(1,"Base:%i %i",nMotorEncoder[base],baseStartingPos);
		nxtDisplayCenteredTextLine(2,"Top:%i %i",nMotorEncoder[top], topStartingPos);
		nxtDisplayCenteredTextLine(3,"Sonar:%i",SensorValue[sonarSensor]);
		nxtDisplayCenteredTextLine(4,"Color:%i",SensorValue[colorSensor]);
}

void init(){
	bFloatDuringInactiveMotorPWM = false;
	baseVal = 0;
	topVal = 0;
}

task main()
{
	init();

	//Store centered position
	baseStartingPos = nMotorEncoder[base];
	topStartingPos = nMotorEncoder[top];

	while(true){
		int my_message=0;

		debug();

		//Update Variables
		baseVal = nMotorEncoder[base];
		topVal = nMotorEncoder[top];

		//Return Joystick to initial position
		if(baseVal!=baseStartingPos)
			motor[base] =baseStartingPos-baseVal-2;
		else
			motor[base] = 0;
		if(topVal!=topStartingPos)
			motor[top] = (topStartingPos-topVal)*5;
		else
			motor[top] = 0;

		//Run Robots actions
		if(topStartingPos-topVal>threshold){
			//PlaySound(soundShortBlip);
			my_message=4;
		}
		else if(topStartingPos-topVal<-threshold)
			my_message=3;
		else if(baseStartingPos-baseVal>threshold){
			//PlaySound(soundBlip);
			my_message=1;
		}
		else if(baseStartingPos-baseVal<-threshold)
			my_message=2;
		else
			my_message=5;

		//Arm Control
		if(SensorValue[touchSensor]==1){
			if(baseStartingPos-baseVal>threshold)
				my_message=100;
			else if(baseStartingPos-baseVal<-threshold)
				my_message=101;
	 		PlayImmediateTone(SensorValue[sonarSensor] * 5 + 220, 10);
	 	}

	 	//Sonar Sensor for Claw Control
	 	if(SensorValue[sonarSensor]<20)
	 		my_message=200;
	 	if(SensorValue[sonarSensor]>25&&SensorValue[sonarSensor]<30)
	 		my_message=201;

 		sendMessage(my_message);
		wait1Msec(10);
	}
}
